language: node_js
node_js: stable
before_script:
- npm install -g gulp
script: gulp build --prod
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: notaddedyet
  app:
    master: moji-prototype
  on:
    repo: ministryofjustice/clarity-prototype-kit
