language: node_js
node_js: stable
before_script:
- npm install -g gulp
script: gulp build --prod
deploy:
  provider: heroku
  buildpack: nodejs
  skip_cleanup: true
  api_key:
    secure: bzkrzay+WipWWECexZN1b0nmfzbeAosta3NHpnfLwT/0RRYCuywSMruqQchaPAgX4hKXK4rGeh1L+nyyNTnpX2NRLDtm/LbNDVIJ1rG36Cb1hpYp+AR7TCZ9qJkBMHwczU4TPCKrcWg18RumP+mVFpOwcvM3e7csmnCzm02Qc9NVFNT/2LrmtEf0DgXRndchj4jzLv20vnFMV9+67dD3EIVhYwyn2h16/csvxoTwqORpItkSvFiASvfxxmBvTcUYkuXBWPezWRVhhYvT2I69zwsQCy2alaT00YZMmwrYL6oikXIdhiF15v2z+WOmZZ2PUMXNzQnvfNWExw8pBNnBJqHYO1RSqU4DuA30qaSRVvMWfbyi/D/Bxptq+Ejg7/+dk6SYne8lLVBFMV7XJNh/kVFIz6uShKvab3I7/SvLB7SsoZVwZVB/M079IPJJdzh4Nn+piqsRxUWoOxjIJek/FQTwfDl9yBOYhiGyAboZq6hMg2T1JUJQnUGx7cNOvpT4CR63Vggm1ymF4OsLFq+NCFGhMgSoUfwlGNfQjaLgOw9yNqBt/DjR6x8i+EITLHnJ4ywRqvzfSrMPWicYtLiA3Tvl9QvOQXIYJ1I3OlDr8sK4wnqUQYEUDHdB7PAi/2visuQ1TXVvcwkSGNE8F4ZoZivHc7Lw+aGv1HAiflFY74k=
  app:
    master: moji-prototype
    dev: moji-prototype-dev
  on:
    repo: ministryofjustice/clarity-prototype-kit
  run:
    - "node server.js"
